let name = prompt ("Vad heter du?")
console.log (`Name: ${name}`)
let age = prompt ("Hur gammal är du?")
console.log (`Ålder: ${age}`)
let adress = prompt ("Vad är din adress?")
console.log (`Adress: ${adress}`)
let postnummer = prompt ("Vad är ditt postnummer?")
console.log (`\t \t ${postnummer}`)
let nummer = prompt ("Vad är ditt telefonnummer?")
console.log (`Telefon: ${nummer}`)